export const FETCH_TESTS_START = 'FETCH_TESTS_START';
export const FETCH_TESTS_SUCCESS = 'FETCH_TESTS_SUCCESS';
export const FETCH_TESTS_ERROR = 'FETCH_TESTS_ERROR';
export const FETCH_TEST_SUCCESS = 'FETCH_TEST_SUCCESS';
